name: Backend - Pull Request - Test

on:
  pull_request:

concurrency:
  group: build-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test-and-build:
    name: Test and build
    uses: CycriLabs/eam-gha-workflows/.github/workflows/be_pull-request_test-build.yml@main
    secrets: inherit
    with:
      java-version: 17
